name: Save Kubesphere Images

on:
  workflow_dispatch:

jobs:
  save-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Extract image list
        run: |
          grep -Eo '^[^#][^ ]+' kubesphere-images.txt > image-list.txt
          echo "Found $(wc -l < image-list.txt) images"

      - name: Pull all images
        run: |
          while read -r image; do
            echo "Pulling $image..."
            docker pull $image || echo "Failed: $image"
          done < image-list.txt

      - name: Save all images to tar
        run: |
          docker save $(cat image-list.txt | tr '\n' ' ') -o Kubesphere-v4.1.3.tar

      - name: Upload image tarball
        uses: actions/upload-artifact@v4
        with:
          name: Kubesphere-v4.1.3
          path: Kubesphere-v4.1.3.tar
